services:
  blogapi:
    build:
      context: .
      dockerfile: ./BlogApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - blogapi_default

  blogplatform:
    build:
      context: .
      dockerfile: ./BlogPlatform/Dockerfile
    ports:
      - "5037:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - blogapi_default
    depends_on:
      - blogapi


networks:
  blogapi_default:
    driver: bridge